services:
  booking-database:
    container_name: booking-db
    image: postgres:18
    ports: ["54321:5432"]
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: bookings
    networks:
      - booking-network
      - bilcool

  db-migration-booking:
    image: amacneil/dbmate
    entrypoint: ["/bin/sh", "-c",  "dbmate --wait --migrations-dir /migrations migrate"]
    volumes:
      - "./internal/pkg/booking/migrations:/migrations"
    depends_on:
      - booking-database
    environment:
      DATABASE_URL: postgres://postgres:postgres@booking-db:5432/bookings?sslmode=disable
    networks:
      - booking-network

networks:
  booking-network:
  bilcool:


